### ISSUE TITLE
Phavuer で Particle は使えますか？

### ISSUE THREAD

**Issue by tkawaguchi-uhuru** [laineus/phavuer#1]
@laineus さん はじめまして

Phavuer とても気に入っております。
Phavuer を使って2Dゲームを開発していますがとても楽しいです。

ところで掲題の通り、
弾のエフェクトなどに Particle を使いたいのですが可能でしょうか？

- 1) Phavuer 本体に Particle を追加する
- 2) Phaser3 で Particle を作って Phavuer scene に追加する
- 3) Particle を諦めて sprite と tween で工夫する

などの方法を想像しているのですが 2の方向性で手元でやってみても
なかなか正解に辿り着けず。。。

laineus さんだとどのように実現するのが良いとお考えでしょうか？

**Comment by laineus** [comment]
@tkawaguchi-uhuru ありがとうございます！

2の方法は手っ取り早いと思います。

コンポーネントの中でsceneを取得してしまえば、そこからは通常のphaser同様に操作できるかと思います。

```js
export default {
  setup () {
    const scene = useScene()
    scene.add.particles(...)
  }
}
```

期待通りいかない点がございましたら、コードをいただければ何か答えられるかもしれません。

**Comment by tkawaguchi-uhuru** [comment]
@laineus   ご回答ありがとうございます！

こちらのヒントをもとにもう少し工夫してみます。
行き詰まったらコードをお送りいたします。

よろしくお願いします 🙏

**Comment by tkawaguchi-uhuru** [comment]
@laineus さん
うまくいきました！

期待通りに Particle を制御できるようになりました。
ありがとうございます。

（私の問題の本質は Particle の初期化オブジェクトに無用な引数を加えていたため、
正しく描画ができていなかった。という内容でした。）

---

現在は Phaser3 も勉強しながらなのでヨチヨチ歩きですが
Vue とても好きなので Phavuer のアイデアにすごく共感しています。

laineus さんの今後のご活躍を楽しみにしています！ ✨

**Comment by laineus** [comment]
ありがとうございました！(返信漏れていてすみません)
クローズします
